---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ if .Values.workbench.subdomain_prefix }}    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/cauth/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/login/"
{{ else }}    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.workbench.domain }}/cauth/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.workbench.domain }}/login/"{{ end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.workbench.domain }}
    - '*.{{ .Values.workbench.domain }}'
    secretName: {{ .Values.tls.secretName }}-auth
  rules:
{{ if .Values.workbench.subdomain_prefix }}  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}{{ else }}  - host: {{ .Values.workbench.domain }}{{ end }}
    http:
      paths:
      - path: /logs
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-open
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.workbench.domain }}
    - '*.{{ .Values.workbench.domain }}'
  rules:
{{ if .Values.workbench.subdomain_prefix }}  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}{{ else }}  - host: {{ .Values.workbench.domain }}{{ end }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 30001
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /landing
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /cauth
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /shared
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /bower_components
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /node_modules
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /asset
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /swagger.yaml
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
      - path: /ConfigModule.js
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ if .Values.certmgr.cluster_issuer }}    cert-manager.io/cluster-issuer: "{{ .Values.certmgr.cluster_issuer }}"{{ else if .Values.certmgr.issuer }}    cert-manager.io/issuer: "{{ .Values.certmgr.issuer }}"{{ end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{ if .Values.workbench.subdomain_prefix }}    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/landing/"{{ else }}    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.workbench.domain }}/landing/"{{ end }}
  name: {{ .Release.Name }}-root
  namespace: {{ .Release.Namespace }}
spec:
  rules:
{{ if .Values.workbench.subdomain_prefix }}  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}{{ else }}  - host: {{ .Values.workbench.domain }}{{ end }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.workbench.domain }}
    - '*.{{ .Values.workbench.domain }}'
    secretName: {{ .Values.tls.secretName }}
